// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUcIpcEvTHQkCtPPhLIRjAyQMhSEyS4sI',
    appId: '1:663803872729:web:d89c49bec53eec692045c8',
    messagingSenderId: '663803872729',
    projectId: 'fatwa-c7756',
    authDomain: 'fatwa-c7756.firebaseapp.com',
    databaseURL: 'https://fatwa-c7756-default-rtdb.firebaseio.com',
    storageBucket: 'fatwa-c7756.appspot.com',
    measurementId: 'G-TJ36ZQHF16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmV0h0sTSfKgDjgxfcmnBLilheAa5csg',
    appId: '1:663803872729:android:9e7ae933ce760e8e2045c8',
    messagingSenderId: '663803872729',
    projectId: 'fatwa-c7756',
    databaseURL: 'https://fatwa-c7756-default-rtdb.firebaseio.com',
    storageBucket: 'fatwa-c7756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP2cIT6QNi1SrqRthQMKGVmk5bXW1jDfA',
    appId: '1:663803872729:ios:ccbb90bf7edc01422045c8',
    messagingSenderId: '663803872729',
    projectId: 'fatwa-c7756',
    databaseURL: 'https://fatwa-c7756-default-rtdb.firebaseio.com',
    storageBucket: 'fatwa-c7756.appspot.com',
    iosClientId: '663803872729-3u0hr0ani41511srmsipk6qj4apm60i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fatwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP2cIT6QNi1SrqRthQMKGVmk5bXW1jDfA',
    appId: '1:663803872729:ios:ccbb90bf7edc01422045c8',
    messagingSenderId: '663803872729',
    projectId: 'fatwa-c7756',
    databaseURL: 'https://fatwa-c7756-default-rtdb.firebaseio.com',
    storageBucket: 'fatwa-c7756.appspot.com',
    iosClientId: '663803872729-3u0hr0ani41511srmsipk6qj4apm60i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fatwa',
  );
}
